-- Chat hỗ trợ giữa khách (guest/user) và shop.
CREATE TABLE conversation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(255) NOT NULL UNIQUE,
    customer_name   VARCHAR(255),
    customer_email  VARCHAR(255),
    created_at      TIMESTAMP,
    last_message_at TIMESTAMP,
    last_message    VARCHAR(2000),
    unread_admin    INTEGER DEFAULT 0,
    unread_customer INTEGER DEFAULT 0
);

CREATE TABLE chat_message (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES conversation (id) ON DELETE CASCADE,
    sender          VARCHAR(20)   NOT NULL,   -- CUSTOMER | ADMIN
    content         VARCHAR(2000) NOT NULL,
    created_at      TIMESTAMP
);

CREATE INDEX idx_chat_message_conversation ON chat_message (conversation_id);
CREATE INDEX idx_conversation_last_message_at ON conversation (last_message_at);
