-- Quản lý danh mục động: bảng category + product tham chiếu category_id (FK).

CREATE TABLE category (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    description VARCHAR(500),
    sort_order  INTEGER
);

-- 6 danh mục ban đầu (tên tiếng Anh, mô tả tiếng Việt).
INSERT INTO category (name, description, sort_order) VALUES
    ('Storage Baskets',     'Giỏ đựng đồ, giỏ quần áo, giỏ có nắp, giỏ picnic', 1),
    ('Trays & Organizers',  'Khay, mẹt, khay trà, hộp khăn giấy, hộp lưu trữ',  2),
    ('Home Decor',          'Gương, decor treo tường, bình trang trí, đồ decor', 3),
    ('Lighting',            'Đèn thả, đèn bàn, chao đèn',                        4),
    ('Planters',            'Giỏ trồng cây, chậu bọc mây, giỏ treo',            5),
    ('Laundry & Bathroom',  'Giỏ giặt, khay phòng tắm, hộp đựng đồ vệ sinh',    6);

-- product: text category -> category_id (FK). Backfill theo tên đang lưu.
ALTER TABLE product ADD COLUMN category_id BIGINT;
UPDATE product SET category_id = c.id FROM category c WHERE product.category = c.name;
ALTER TABLE product ADD CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES category (id);
ALTER TABLE product DROP COLUMN category;
